on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Test and lint
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo contents
        uses: actions/checkout@v1

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Test
        env:
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        run: |
          if ["$CONFIG_JSON" != ""]; then
            echo "$CONFIG_JSON" | base64 --decode > config.json
            npm run test
          else
            npm run test-pr
          fi

      - name: Lint
        run: npm run lint